require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SynonymsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Synonym. As you add validations to Synonym, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SynonymsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all synonyms as @synonyms" do
      synonym = Synonym.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:synonyms)).to eq([synonym])
    end
  end

  describe "GET show" do
    it "assigns the requested synonym as @synonym" do
      synonym = Synonym.create! valid_attributes
      get :show, {:id => synonym.to_param}, valid_session
      expect(assigns(:synonym)).to eq(synonym)
    end
  end

  describe "GET new" do
    it "assigns a new synonym as @synonym" do
      get :new, {}, valid_session
      expect(assigns(:synonym)).to be_a_new(Synonym)
    end
  end

  describe "GET edit" do
    it "assigns the requested synonym as @synonym" do
      synonym = Synonym.create! valid_attributes
      get :edit, {:id => synonym.to_param}, valid_session
      expect(assigns(:synonym)).to eq(synonym)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Synonym" do
        expect {
          post :create, {:synonym => valid_attributes}, valid_session
        }.to change(Synonym, :count).by(1)
      end

      it "assigns a newly created synonym as @synonym" do
        post :create, {:synonym => valid_attributes}, valid_session
        expect(assigns(:synonym)).to be_a(Synonym)
        expect(assigns(:synonym)).to be_persisted
      end

      it "redirects to the created synonym" do
        post :create, {:synonym => valid_attributes}, valid_session
        expect(response).to redirect_to(Synonym.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved synonym as @synonym" do
        post :create, {:synonym => invalid_attributes}, valid_session
        expect(assigns(:synonym)).to be_a_new(Synonym)
      end

      it "re-renders the 'new' template" do
        post :create, {:synonym => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested synonym" do
        synonym = Synonym.create! valid_attributes
        put :update, {:id => synonym.to_param, :synonym => new_attributes}, valid_session
        synonym.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested synonym as @synonym" do
        synonym = Synonym.create! valid_attributes
        put :update, {:id => synonym.to_param, :synonym => valid_attributes}, valid_session
        expect(assigns(:synonym)).to eq(synonym)
      end

      it "redirects to the synonym" do
        synonym = Synonym.create! valid_attributes
        put :update, {:id => synonym.to_param, :synonym => valid_attributes}, valid_session
        expect(response).to redirect_to(synonym)
      end
    end

    describe "with invalid params" do
      it "assigns the synonym as @synonym" do
        synonym = Synonym.create! valid_attributes
        put :update, {:id => synonym.to_param, :synonym => invalid_attributes}, valid_session
        expect(assigns(:synonym)).to eq(synonym)
      end

      it "re-renders the 'edit' template" do
        synonym = Synonym.create! valid_attributes
        put :update, {:id => synonym.to_param, :synonym => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested synonym" do
      synonym = Synonym.create! valid_attributes
      expect {
        delete :destroy, {:id => synonym.to_param}, valid_session
      }.to change(Synonym, :count).by(-1)
    end

    it "redirects to the synonyms list" do
      synonym = Synonym.create! valid_attributes
      delete :destroy, {:id => synonym.to_param}, valid_session
      expect(response).to redirect_to(synonyms_url)
    end
  end

end
